
ROM_NAME      = Print_Test
CONFIG        = LOROM_1MBit_copyright
API_MODULES   = reset-snes math block text text8x8
API_DIR       = ../../
SOURCE_DIR    = .
RESOURCES_DIR = resources

include $(API_DIR)/Makefile.in
